
name: slayawaycamp

cflags:
  - -std=c17

cxxflags:
  - -std=c++23
  - -Werror=return-type

macros:
  SLAYAWAYCAMP_MOVIES_DIR: '""'
  SLAYAWAYCAMP_REFERENCE_DIR: '""'

includes:
  - ~/opt/qt-5.15.9-release/include
  - ~/opt/qt-5.15.9-release/include/QtCore

files:
  - .

exclude:

ignore:
